"""The Phase 4 Stage-2 report writer — M2, under the A47 ruling.

One long markdown template plus the tables computed for the report alone. Like
``report.py`` it decides nothing; ``scripts/07_fit_m2.py`` does.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from . import evaluate, features, interventions, policy
from .challenger import SHIP_MARGIN_AUC
from .fairness import PROXY_RATIO_LIMIT
from .report import md_table

LK03_LIMIT = 0.85
FEASIBILITY_GATE = 0.72
MED_TIER_FLOOR = 0.10  # blueprint §8.3


def pstar_tiers(score: np.ndarray, pstar: float) -> pd.Series:
    """Blueprint §8.3's economically anchored tiers. Not percentiles."""
    return pd.Series(np.where(score >= pstar, "HIGH",
                              np.where(score >= MED_TIER_FLOOR, "MED", "LOW")))


def tier_table(score: np.ndarray, y: np.ndarray, pstar: float) -> pd.DataFrame:
    """Realised shares against §8.3's expected shares, which were priors."""
    tiers = pstar_tiers(score, pstar)
    expected = {"LOW": 45.0, "MED": 38.0, "HIGH": 17.0}
    rows = []
    for tier in ("LOW", "MED", "HIGH"):
        mask = (tiers == tier).to_numpy()
        rows.append({
            "tier": tier,
            "definition": {"LOW": f"p < {MED_TIER_FLOOR:.2f}",
                           "MED": f"{MED_TIER_FLOOR:.2f} <= p < {pstar:.4f}",
                           "HIGH": f"p >= {pstar:.4f} (p*)"}[tier],
            "orders": int(mask.sum()),
            "share_pct": round(float(mask.mean()) * 100, 2),
            "expected_share_pct": expected[tier],
            "observed_rto": round(float(np.asarray(y)[mask].mean()), 4) if mask.any() else np.nan,
        })
    return pd.DataFrame(rows)


def _show_ratio(audit: pd.DataFrame) -> pd.DataFrame:
    """Render `ratio` as text so a numeric column does not print at 4dp beside a
    string one. FA-01's own logic reads the numeric frame, never this."""
    out = audit.copy()
    out["ratio"] = out["ratio"].map(
        lambda v: f"{v:.2f}x" if isinstance(v, (int, float)) else v)
    return out


def _bars(auc: float, ceiling: float) -> str:
    rows = [
        ("Achievable AUC ceiling (`_truth.json`)", f"{ceiling:.4f}",
         "below" if auc < ceiling else "AT OR ABOVE — LEAK"),
        ("LK-03 hard limit", f"{LK03_LIMIT:.2f}", "PASS" if auc < LK03_LIMIT else "FAIL"),
        ("Feasibility gate (§9.4)", f"{FEASIBILITY_GATE:.2f}",
         "full risk-based pricing" if auc >= FEASIBILITY_GATE else "COARSE TIERS ONLY"),
    ]
    body = "\n".join(f"| {n} | {v} | {auc:.4f} | {s} |" for n, v, s in rows)
    return "| Bar | Value | M2 test | Status |\n|---|---|---|---|\n" + body


def write_report(ctx: dict, truth: dict, path) -> None:
    ceiling = truth["achieved"]["auc_ceiling_precheckout"]
    pstar = truth["economics_targets"]["breakeven_rto_probability_derived"]
    ann = truth["economics_targets"]["annualization_factor_derived"]

    split, model, p_test, y_test = ctx["split"], ctx["model"], ctx["p_test"], ctx["y_test"]
    test, cm, gbm = ctx["test"], ctx["cm"], ctx["gbm"]
    m2_auc = ctx["m2_auc"]

    coefs = model.coefficients()
    top = coefs[coefs["feature"] != "(intercept)"].head(20)[
        ["feature", "coef_per_sd", "odds_ratio_per_sd", "p_value"]]
    exclusions = pd.DataFrame(
        [{"column": k, "reason": v} for k, v in features.EXCLUSIONS.items()])

    audit_global = policy.ratio_audit(test, p_test, "global")
    audit_tiered = policy.ratio_audit(test, p_test, "per-tier")
    cost = policy.margin_cost(test, p_test, cm, ann)
    exposure_g = policy.tier_exposure(test, p_test, 0.17, "global", pstar)
    exposure_t = policy.tier_exposure(test, p_test, 0.17, "per-tier", pstar)
    sensitivity = policy.conversion_sensitivity(
        test, p_test, cm, ctx["prepaid"], ann, 0.17)
    gradient = policy.protection_gradient(test)

    at17 = cost[cost["volume_flagged"] == 0.17].iloc[0]
    t3_g = exposure_g.set_index("geo_tier").loc["TIER3"]
    t3_t = exposure_t.set_index("geo_tier").loc["TIER3"]
    metro_t = exposure_t.set_index("geo_tier").loc["METRO"]
    worst_ratio = max(r for r in audit_tiered["ratio"] if isinstance(r, (int, float)))
    fa01 = "PASS" if (audit_tiered["verdict"] == "PASS").all() else "FAIL"

    text = """# Phase 4 — Stage 2: M2 (post-selection), under the A47 ruling

Generated by `scripts/07_fit_m2.py`. Every figure is measured on the dataset or
read from `data/truth/_truth.json`. Nothing is quoted from spec prose.

This report exists because the §8.4 escalation raised in
`reports/phase4_m1.md` §6 was **ruled on** — option 3, per-tier thresholds, with
three conditions. `docs/phase4_escalation.md` is the standalone record of the
finding and the ruling. This is the model fitted under it.

M2 is the **post-selection** model: it sees `payment_method`, `paid_via_switch`
and `payment_attempt_count`, which M1 had to project away. That is the only
difference in the feature set, and it is why **p\\* = {pstar:.4f} applies here and
did not apply to M1** — p\\* is the break-even of a *COD* order, and M2 is the
first model that knows whether the order is one.

---

## 1. Population and split

Identical to M1's, and for the same reasons — the censoring-horizon cut at
2026-03-07 and the time-based split are derived in `reports/phase4_m1.md` §1-2
and not re-argued here. Using a different population would make the two models
incomparable, which is the one thing this report needs them to be.

{splits}

Cut date **{cut}**. Base rate **{base:.4f}** on test.

## 2. Scoreboard

{scoreboard}

{bars}

**M2 sits {gap:.4f} below the ceiling, and that is the right side of it.** The
{ceiling:.4f} ceiling in `_truth.json` is computed *with* `is_cod` known, which is
exactly M2's information set — so unlike M1, M2 is measured against a ceiling it
is entitled to approach. It approaches without touching. The train figure
({train_auc:.4f}) sits closer still; the train-test gap is the honest cost of
fitting 51 coefficients on 50,408 rows.

**The baseline is finally the real one.** Blueprint §9.3's floor is "payment
method + prior RTO + tenure" — three rules. M1 could only have two of them and the
M1 report said so rather than quietly scoring itself against a floor it never
competed with. M2 has all three, and beats them by **{rules_margin:.1f}pp** of AUC.

`order_risk_tier_rule_based` is deliberately **not** in `vw_risk_model_input` — it
embeds payment method. Rather than widen the firewall it is **reconstructed** from
two columns that are in the view: `pit_risk_tier_rule_based`, escalated one tier
for COD. That reconstruction was checked against the planted column on all
{verify_n:,} test rows and agrees on **{verify_pct:.2f}%** of them.

{rules_table}

### The GBM challenger

{gbm_scoreboard}

**{gbm_verdict}**

Blueprint §9.3 pre-committed to this rule — ">= {ship_margin:.0f}pp AUC **and** >= INR X in
simulated CM, otherwise the interpretability is worth more" — before anyone had
either number. The margin here is **{gbm_margin:+.2f}pp**, so the CM half of the
test is never reached. Note the challenger's *train* AUC of {gbm_train:.4f}, which
is above the {ceiling:.4f} achievable ceiling: that is capacity, not signal, and
it is precisely what the 3pp margin exists to refuse to pay for.

## 3. Calibration

The thresholds below are absolute probabilities tied to money, so this section
outranks the AUC. A model that ranks perfectly and reports 0.31 where the truth
is 0.19 restricts orders that are in fact profitable.

{reliability}

Calibration slope **{slope:.4f}** (1.0 perfect), intercept **{intercept:.4f}**
(0.0 perfect), ECE **{ece:.5f}**, Brier **{brier:.5f}**.

### Risk deciles

{deciles}

## 4. Feature importances

Per standard deviation, so |coefficient| is the importance directly. Top 20 of
{n_features}:

{coefs}

`payment_method[COD]` enters at **{cod_coef:+.4f}** per SD — the largest single
coefficient in the model, and the feature M1 was defined not to have. Read it as
a *predictive* weight, not a causal one: `_truth.json` records the planted logit
coefficient as +1.60 and the true average marginal effect as
{ame:.2f}pp against a naive observed gap of {naive:.2f}pp, so
{selection:.1%} of what a naive reading of this row would attribute to COD is
selection. The model is not wrong to use it. A slide that called it "the causal
effect of COD" would be.

### The scorecard

{points}

### What is not in the model, and why

{count_cull_note}

{exclusions}

**The Stage-4 bar held again.** `attempt_delay_days` and `delivery_delay_days`
are absent from the view, from the design matrix, and asserted absent by name in
`dataset.assert_firewall`. M2's larger feature set does not relax it.

## 5. The p\\*-anchored tiering

M2 is the first model entitled to §8.3's economic cut-lines, and they are cut
lines, not percentiles: LOW below 10%, HIGH at or above p\\* = {pstar:.4f}, where a
COD order's expected contribution margin is exactly zero.

{tiers}

**The HIGH tier is {high_share:.1f}% of traffic, not the ~17% §8.3 expected.**
That is not a modelling error and it should not be tuned away. §8.3's shares were
priors written against the project's headline blended RTO rate of 16.53%; this
population is the *uncensored window*, whose base rate is {base:.4f}. A higher
base rate puts more mass above a fixed economic threshold. The threshold is the
thing that was pre-committed to; the share is an output.

## 6. The ruling applied — per-tier thresholds

### 6.1 Which levers are rationed by geography (condition 1)

Restrictive interventions rank within tier. Offers use the global score. The
ruling's phrasing is the test: **carrots are not rationed by geography; sticks
are.**

{interventions}

**`E` was reclassified as restrictive (decision A48).** It was first listed as an
offer because reordering removes nothing. That was wrong: E **de-emphasises** as
well as emphasises, and for a payment method chosen by 62% of orders largely out
of habit, salience *is* the option. A lever expected to move prepaid share by
3-6pp through position alone exercises the same power as a fee while requiring
none of a fee's disclosure. It ranks per-tier, and it carries a hard floor into
the Phase 5 PRD:

> {one_tap}

### 6.2 The audit, both rules

Both tables are measured **after** the §8.4 customer-level protections run,
because that is what a customer actually experiences and therefore what FA-01
asserts on. `reports/phase4_m1.md` §6.1 measured the same audit *before* them,
because there the question was what the score was doing rather than what the
policy would do. The two are not interchangeable: M1's global rule reads 52.6%
of Tier-3 pre-overlay and 42.3% post-overlay at the same 17% volume.

**Global thresholds — the M1 failure, reproduced on M2:**

{audit_global}

**Per-tier thresholds — the ruling:**

{audit_tiered}

**FA-01: {fa01}.** Worst tier over best tier peaks at **{worst_ratio:.2f}x**
against the {limit}x limit, at every volume in
{volumes}.

The ratio is not 1.00, and the reason is worth stating rather than smoothing.
Per-tier thresholds equalise the *selection* exactly: at the §8.3 volume,
17.00% of every tier is selected before anything else runs. The §8.4 customer-level protections then veto
different shares in different tiers, because clean records are not evenly
distributed: Metro customers have more of them, so more Metro selections are
vetoed and Metro's final rate lands lowest. **The residual spread is caused by a
protection, not by the score.** Measured rather than asserted:

{gradient}

A clean record is three delivered orders and zero prior RTO. Tier-3 runs
{rto_spread:.1f}x Metro's RTO rate, so half as many Tier-3 customers hold one —
{clean_metro:.1f}% in Metro against {clean_t3:.1f}% in Tier-3. Zero-history immunity, by contrast, is almost flat across
tiers (~{zero_flat:.1f}%), so essentially all of the residual gradient comes from
the clean-record cap. It is the fairness overlay's own gradient showing through,
and at {worst_ratio:.2f}x it is well inside the {limit}x limit.

### 6.3 What the constraint costs (condition 2)

Both arms restrict the **same selected volume** — the `selected` column — so the
only difference between them is *which* orders they choose. The `_n` columns are
what survives the overlay veto and differ slightly for the reason in §6.2.

The counterfactual is stated once and applied identically to both arms: a
restricted order **does not happen**, so its realised contribution margin goes to
zero and the policy's effect on it is `-cm`. An RTO carries a negative margin, so
removing it is a gain; a delivered order carries a positive one, so removing it is
a loss. This is §10.2's own frame — *above p\\*, an abandoned order is a saving* —
and it puts no behavioural parameter anywhere in the arithmetic.

{cost}

**The price of the fairness constraint, at the §8.3 volume of 17%, is
₹{price:,.0f} across a {n_test:,}-order test window — ₹{price_per:,.2f} per
restricted order, or ₹{price_cr:.2f} Cr a year** at the derived annualisation
factor of {ann:.1f}. That is the number the ruling asked to have on the record.

For scale: the project's headline RTO exposure is ~₹165 Cr a year. The fairness
constraint costs **{price_pct:.1f}% of that**, and it buys a policy that can be
defended to a customer, a regulator, or a journalist.

**The price is robust to the behavioural response.** If restricted COD orders
switch to prepaid rather than abandoning — earning the prepaid economics measured
on this dataset, ₹{switch_ev:.2f} per switched order — both arms improve together
and the gap barely moves:

{sensitivity}

The switch shares are a **sweep, not an estimate**. Nobody has measured the switch
rate on this platform; §10.1's -20 to -30pp figures are Phase 1 priors written
down to be tested. What the sweep establishes is that the answer to "what does
fairness cost" does not depend on picking a point inside that range.

### 6.4 What per-tier thresholding does to Tier-3's absolute exposure (condition 3)

Equalising the ratio is not the same as making Tier-3's exposure acceptable, and
the ruling was right to ask for the level separately. At the 17% volume:

**Global:**

{exposure_global}

**Per-tier:**

{exposure_tiered}

Three things, in the order that matters:

1. **Tier-3's absolute restriction rate falls from {t3_g:.1%} to {t3_t:.1%}.**
   Under the global rule the policy restricted more than **two in five** Tier-3
   orders. Under the ruling it restricts about one in seven. The answer to
   condition 3 is that the absolute exposure does not merely become *equal*, it
   becomes roughly a third of what it was.

2. **The cost lands exactly where the objection said it would.** Metro's
   restricted set has a mean score of {metro_score:.4f} and a realised RTO rate of
   {metro_rto:.1%} — and **{metro_below:.1%} of those orders score below p\\***,
   which means their expected contribution margin as COD orders is *positive*. The
   policy restricts them anyway. That is not a defect in the implementation; it is
   the trade, and §6.3 is what it costs.

3. **Under-restriction is the mirror image, and it is the part a fairness
   framing can hide.** Tier-3's restricted orders carry a {t3_rto:.1%} realised
   RTO rate against Metro's {metro_rto:.1%}. Per-tier thresholding does not make
   Tier-3 safe; it stops the policy from *pricing* how unsafe it is. Both tiers
   are cut at their own 83rd percentile, so a Tier-3 order just below that cut
   goes unrestricted while a Metro order just above it is restricted at
   **{risk_multiple:.1f}x less risk**. Nothing about equalising the ratio makes
   that comparison go away, and anyone presenting this policy should say so
   before someone else does.

---

## 7. Verdict

{verdict}
""".format(
        pstar=pstar, splits=md_table(split.describe()), cut=split.cut_date.date(),
        base=float(np.mean(y_test)),
        scoreboard=md_table(ctx["scoreboard"]), bars=_bars(m2_auc, ceiling),
        gap=ceiling - m2_auc, ceiling=ceiling, train_auc=ctx["train_auc"],
        rules_margin=(m2_auc - ctx["rules_auc"]) * 100,
        verify_n=ctx["verify"]["rows_compared"],
        verify_pct=ctx["verify"]["agreement"] * 100,
        rules_table=md_table(ctx["rules_table"]),
        gbm_scoreboard=md_table(gbm["scoreboard"]), gbm_verdict=gbm["verdict"],
        gbm_margin=gbm["margin_pp"], gbm_train=gbm["train_auc"],
        ship_margin=SHIP_MARGIN_AUC * 100,
        reliability=md_table(evaluate.reliability(y_test, p_test)),
        slope=ctx["scoreboard"].iloc[-1]["cal_slope"],
        intercept=ctx["scoreboard"].iloc[-1]["cal_intercept"],
        ece=ctx["scoreboard"].iloc[-1]["ece"],
        brier=ctx["scoreboard"].iloc[-1]["brier"],
        deciles=md_table(evaluate.decile_lift(y_test, p_test)),
        n_features=ctx["n_features"], coefs=md_table(top),
        cod_coef=float(coefs.loc[coefs["feature"] == "payment_method[COD]",
                                 "coef_per_sd"].iloc[0]),
        ame=truth["planted_causal_effects"]["cod_on_rto"]["average_marginal_effect_pp"],
        naive=truth["planted_causal_effects"]["cod_on_rto"]["naive_observed_gap_pp"],
        selection=truth["planted_causal_effects"]["cod_on_rto"]["selection_share_of_naive_gap"],
        points=md_table(model.points().head(14)[["feature", "points_per_sd"]], "{:.2f}"),
        count_cull_note=features.COUNT_CULL_NOTE, exclusions=md_table(exclusions),
        tiers=md_table(tier_table(p_test, y_test, pstar), "{:.4f}"),
        high_share=float((p_test >= pstar).mean()) * 100,
        interventions=md_table(policy.intervention_table()),
        one_tap=interventions.ONE_TAP_CONSTRAINT,
        audit_global=md_table(_show_ratio(audit_global)),
        audit_tiered=md_table(_show_ratio(audit_tiered)),
        gradient=md_table(gradient, "{:.2f}"),
        rto_spread=float(gradient.set_index("geo_tier").loc["TIER3", "tier_rto_rate"])
        / float(gradient.set_index("geo_tier").loc["METRO", "tier_rto_rate"]),
        clean_metro=float(gradient.set_index("geo_tier").loc["METRO", "clean_record_pct"]),
        clean_t3=float(gradient.set_index("geo_tier").loc["TIER3", "clean_record_pct"]),
        zero_flat=float(gradient["zero_history_pct"].mean()),
        risk_multiple=float(t3_t["rto_rate_restricted"]) / float(metro_t["rto_rate_restricted"]),
        fa01=fa01, worst_ratio=worst_ratio, limit=PROXY_RATIO_LIMIT,
        volumes=list(policy.FA01_VOLUMES),
        cost=md_table(cost, "{:.2f}"),
        price=at17["price_of_fairness"], n_test=len(test),
        price_per=at17["price_per_restricted_order"],
        price_cr=at17["price_annualised_cr"], ann=ann,
        price_pct=at17["price_annualised_cr"] / 165 * 100,
        switch_ev=float(sensitivity.iloc[0]["switched_order_ev"]),
        sensitivity=md_table(sensitivity, "{:.2f}"),
        exposure_global=md_table(exposure_g), exposure_tiered=md_table(exposure_t),
        t3_g=float(t3_g["restriction_rate"]), t3_t=float(t3_t["restriction_rate"]),
        metro_score=float(metro_t["mean_score_restricted"]),
        metro_rto=float(metro_t["rto_rate_restricted"]),
        metro_below=float(metro_t["share_below_pstar"]),
        t3_rto=float(t3_t["rto_rate_restricted"]),
        verdict=ctx["verdict"],
    )
    path.write_text(text, encoding="utf-8")
